name: Update Notion Stats

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install @notionhq/client

      - name: Run update script
        run: node update.js
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DB_ANIME_ID: ${{ secrets.DB_ANIME_ID }}
          DB_FILM_ID: ${{ secrets.DB_FILM_ID }}
          DB_SERIES_ID: ${{ secrets.DB_SERIES_ID }}

      - name: Commit counts.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update counts.json"
          file_pattern: counts.json
