name: Update Notion Stats

on:
  schedule:
    - cron: "0 * * * *"     # toutes les heures
  workflow_dispatch:        # exécutable à la main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install @notionhq/client

      - name: Run script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DB_ANIME_ID: ${{ secrets.DB_ANIME_ID }}
          DB_FILM_ID: ${{ secrets.DB_FILM_ID }}
          DB_SERIES_ID: ${{ secrets.DB_SERIES_ID }}
        run: node stats.js

      - name: Commit results
        run: |
          git config user.email "bot@github.com"
          git config user.name "GitHub Bot"
          git add counts.json
          git commit -m "Update stats" || echo "No changes"
          git push
