name: Update Notion Stats

on:
  workflow_dispatch: # permet de lancer manuellement depuis GitHub Actions

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install @notionhq/client

      - name: Run stats script
        run: node update.js

      - name: Commit counts.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update stats
          file_pattern: counts.json
          branch: main
          commit_user_name: github-actions
          commit_user_email: github-actions@github.com
          push_options: "--force" # facultatif, permet de forcer si conflit
