name: Update Notion Stats

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run stats.js
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DB_ANIME_ID: ${{ secrets.DB_ANIME_ID }}
          DB_FILM_ID: ${{ secrets.DB_FILM_ID }}
          DB_SERIES_ID: ${{ secrets.DB_SERIES_ID }}
        run: node stats.js

      - name: Commit and push counts.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update counts.json
          branch: main
          file_pattern: counts.json
          author_name: GitHub Actions
          author_email: actions@github.com
          commit_empty: false
