- name: Commit and push counts.json
  uses: stefanzweifel/git-auto-commit-action@v5
  with:
    file_pattern: counts.json
    commit_message: "Update stats"
    branch: main
    commit_user_name: github-actions
    commit_user_email: github-actions@github.com
    repository: ${{ github.repository }}
    push_options: --force
    token: ${{ secrets.GH_TOKEN }}
