name: Update Notion Stats

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install @notionhq/client

      - name: Run script
        run: node stats.js
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DB_ANIME_ID: ${{ secrets.DB_ANIME_ID }}
          DB_FILM_ID: ${{ secrets.DB_FILM_ID }}
          DB_SERIES_ID: ${{ secrets.DB_SERIES_ID }}

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: counts
          path: counts.json
