name: Update Notion Stats

on:
  workflow_dispatch:  # d√©clenchable manuellement
  schedule:
    - cron: "0 */6 * * *" # optionnel, toutes les 6h

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DB_ANIME_ID: ${{ secrets.DB_ANIME_ID }}
          DB_FILM_ID: ${{ secrets.DB_FILM_ID }}
          DB_SERIES_ID: ${{ secrets.DB_SERIES_ID }}
        run: node update.js

      - name: Commit counts.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update stats"
          file_pattern: counts.json
          branch: main
